@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LinkyTimeParser" as LinkyTimeParser LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant "l:ListMeetingCommand" as ListMeetingCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list")
activate LogicManager

LogicManager -> LinkyTimeParser : parseCommand("list")
activate LinkyTimeParser

create ListMeetingCommand
LinkyTimeParser -> ListMeetingCommand
activate ListMeetingCommand

ListMeetingCommand --> LinkyTimeParser : l
deactivate ListMeetingCommand

LinkyTimeParser --> LogicManager : l
deactivate LinkyTimeParser

LogicManager -> ListMeetingCommand : execute()
activate ListMeetingCommand

ListMeetingCommand -> Model : updateFilteredMeetingList()
activate Model

Model --> ListMeetingCommand
deactivate Model

create CommandResult
ListMeetingCommand -> CommandResult
activate CommandResult

CommandResult --> ListMeetingCommand : result
deactivate CommandResult

ListMeetingCommand --> LogicManager : result
deactivate ListMeetingCommand

[<--LogicManager
deactivate LogicManager
@enduml
