@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Class "<<interface>>\nReadOnlyLinkyTime" as ReadOnlyLinkyTime
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class LinkyTime
Class ModelManager
Class UserPrefs

Package Meeting {
Class Meeting
Class DateTime
Class Duration
Class MeetingName
Class Url
Class IsRecurring
Class UniqueMeetingList
}

Package Tag {
Class Tag
}

Package Module {
Class Module
Class ModuleName
Class UniqueModuleList
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

LinkyTime .up.|> ReadOnlyLinkyTime

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyLinkyTime
ModelManager -left-> "1" LinkyTime
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

LinkyTime *--> "1" UniqueMeetingList
UniqueMeetingList "1" --> "~*" Meeting
Meeting *--> MeetingName
Meeting *--> Url
Meeting *--> Duration
Meeting *--> DateTime
Meeting "*"  --> "1" Module
Meeting *--> IsRecurring
Meeting *--> "*" Tag

ModelManager --> "~* filtered" Meeting

LinkyTime *--> "1\t" UniqueModuleList
UniqueModuleList "1" --> "~*" Module
Module *--> ModuleName

ModelManager --> "~*" Module

@enduml
