@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "LinkyTime Storage" #F4F6F6{
Class "<<interface>>\nLinkyTimeStorage" as LinkyTimeStorage
Class JsonLinkyTimeStorage
Class JsonSerializableLinkyTime
Class JsonAdaptedMeeting
Class JsonAdaptedTag
Class JsonAdaptedModule
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" LinkyTimeStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> LinkyTimeStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonLinkyTimeStorage .up.|> LinkyTimeStorage
JsonLinkyTimeStorage ..> JsonSerializableLinkyTime
JsonSerializableLinkyTime --> "*" JsonAdaptedMeeting
JsonAdaptedMeeting --> "*" JsonAdaptedTag
JsonSerializableLinkyTime --> "*" JsonAdaptedModule

@enduml
