@startuml
!include ../style.puml
start
:User enters delete module command;
:Parse command text;
if () then ([index parameter is valid])
:Delete Module
matching given index;
if () then ([Module with given index exists])
if () then ([isForced])
: Delete all associated meetings;
: Delete module from LinkyTime;
: Show success message to user;
else ([else])
:Check if there are
meetings under this module;
if () then ([No meetings associated])
:Delete module
from LinkyTime;
note left
Saving and
committing of
the state and
data has been
omitted for
brevity.
end note
:Show success
message to user;
else ([else])
:Show Delete restricted
error to user;
endif
endif
else ([else])
:Show Module not found
error to user;
endif
else ([else])
:Show invalid usage
error to user;
endif
stop
@enduml
